# Generated by Django 5.0.6 on 2024-07-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical_activities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=20)),
                ('instruction', models.TextField()),
                ('practical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicals.practicals')),
            ],
        ),
    ]
