# Generated by Django 5.0.6 on 2024-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
