# Generated by Django 5.0.6 on 2024-07-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('practical_activities', '0001_initial'),
        ('practicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='practical_activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practical_activities.practical_activities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='practical_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practicals.practicals'),
            preserve_default=False,
        ),
    ]
