# Generated by Django 5.0.6 on 2024-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
